#!/bin/bash

text="$1"

if [ -z "$text" ]; then
    echo "Please write the thought"
    exit 1
fi

if [ -z "$TELEGRAM_BOT_TOKEN" ]; then
    echo "Please set TELEGRAM_BOT_TOKEN"
    exit 1
fi

data="$(cat<<EOF
{
"chat_id": "@reorx_share",
"parse_mode": "HTML",
"text": "💭 $text #thought"
}
EOF
)"

curl "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
    -X POST -H "Content-Type: application/json" \
    -d "$data"
